name: Docker CI
on:
    push:
        branches:
            master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/iris-classifier .
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/iris-classifier:v2