name: Docker CI

on:
  push:
    branches:
      - cloud-run

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/iris-classifier:v3 .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/iris-classifier:v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy iris-classifier \
            --image docker.io/${{ secrets.DOCKER_USERNAME }}/iris-classifier:v3 \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
